name: parallel-job-example

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  build-and-test-1:
    runs-on: ubuntu-latest
    steps:
      - name: Run custom action
        uses: manhld7/business-greetings-action@main