name: parallel-job-example

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  run-custom-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run custom action
        uses: manhld7/business-greetings-action@main